CREATE DATABASE IF NOT EXISTS 'Self' CHARACTER SET 'utf8',
USE self,

CREATE TABLE IF NOT EXISTS 'Eleve' (
    id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nom VARCHAR(20) NOT NULL,
    prenom VARCHAR(20) NOT NULL,
    credit SMALLINT(5), #Si le regime est externe. Partant du principe que les autres élèves paie un forfait
    classe ENUM(6A,6B,6C,5A,5B,5C,4A,4B,4C,3A,3B,3C,2A,L2A,L2B,L2C,L1SVT,L1SSI,L12DA,L12DB,L12DC,LTSVT,LTSSI,LT2DA,LT2DB,LT2DC),LP2A,LP2B,LP,2C,LP1A,LP1B,LP1C,LPT1A,LPTA,LPTB,LPTC),
    regime' ENUM(Interne, Demi_pensionnaire, Externe),
    adresse' VARCHAR,
    date_naissance' DATE NOT NULL,
    Ville' VARCHAR(20) NOT NULL,
    code_postal SMALLINT(5) NOT NULL,
    info_supp TEXT,
    PRIMARY KEY (ID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS 'Prof'(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	'nom' VARCHAR(20) NOT NULL,
    'prenom' VARCHAR(20) NOT NULL,
    'credit' SMALLINT(5),
    'classe_tit' ENUM(6A,6B,6C,5A,5B,5C,4A,4B,4C,3A,3B,3C,2A,L2A,L2B,L2C,L1SVT,L1SSI,L12DA,L12DB,L12DC,LTSVT,LTSSI,LT2DA,LT2DB,LT2DC),LP2A,LP2B,LP,2C,LP1A,LP1B,LP1C,LPT1A,LPTA,LPTB,LPTC),
	'adresse' VARCHAR,
    'date_naissance' DATE NOT NULL,
    'ville' VARCHAR(20) NOT NULL,
    'code_postal' SMALLINT(5) NOT NULL,
    'info_supp' TEXT,
    PRIMARY KEY (ID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS 'Admin' (
	'id' SMALLINT USIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	'nbr_rps_prevu' SMALLINT NOT NULL,
	'nbr_rps_servi' SMALLINT NOT NULL,
	PRIMARY KEY (ID)
)ENGINE=INNODB;
